### ISSUE TITLE
Support Img Tag

### ISSUE THREAD

**Issue by markwk** [dillionmegida/gatsby-remark-liquid-tags#1]
This looks like a great start to solving one of my problems migrating off of Octopress / Jekyll to Gatsby for my blog. Specifically, I have several hundred posts that use liquid img tags in markdown and look like this: 

`{% img center /images/path-to-image.jpg %}`

I see we'll need to create an embed file like images.js with a getImage function. 

Any suggestions on how we'd parse this to take in case, position and url path? 

Thanks!

**Comment by dillionmegida** [comment]
It's a great idea. 
I'd start work on it now.

Just for clarification, the liquid tag above transforms to,

`<img src='path/file.ext' width='100%'/> `right?

And what's the function of center?
Please state more details.

**Comment by markwk** [comment]
Awesome! Here's how it was architected with Octopress: http://octopress.org/docs/plugins/image-tag/

Syntax looks like this: 

`{% img [class names] /path/to/image [width] [height] [title text [alt text]] %}`

**Comment by dillionmegida** [comment]
I went through the documentation referenced. Honestly, I don't still understand it completely.

I'm hoping you can be clearer.

**Comment by markwk** [comment]
I'm not sure I can make it much clearer than that referenced page. But here is a specific example:

The markdown submitted looks like this:

`{% img left http://placekitten.com/320/250 Place Kitten #2 %}`

This then generates the following html markup: 

`<img class="left" src="http://placekitten.com/320/250" title="Place Kitten #2">`

I'm mostly confused by the parsing aspect where we convert the markdown to variables which we then generate output accordingly.

**Comment by dillionmegida** [comment]
This is clearer now.

Also to confirm,
`{% img left http://placekitten.com/320/250 200 200 'Place Kitten #2' 'A kitten' %}`

translates to
`<img class="left" src="http://placekitten.com/320/250" width='200px' height='200px' title="Place Kitten #2" alt='A kitten'>`

Right?

**Comment by markwk** [comment]
@dillionmegida You got it.

**Comment by dillionmegida** [comment]
Okay. I'd start work on it tomorrow.

**Comment by markwk** [comment]
Any luck? If you can throw me some guidelines, I'd love to contribute on this.

**Comment by dillionmegida** [comment]
I had a busy week, so I just took it up yesterday. The plug-in requires a refractoring, please give me little more time.

It's basically built with JavaScript. I used a plug-in which visits all parts of the markdown, thereby converting the liquid tags. You can go through the source code. I commented most parts of it.

**Comment by dillionmegida** [comment]
Hi @markwk, I don't think this request would be feasible. It beats the purpose of this plugin which is to embed services by the URL. This is just an image markup which can be simply done with an image tag.

So I'd close this now. I'm still open for more interesting ideas 🙂

**Comment by dillionmegida** [comment]
Hi @markwk, I don't think this request would be feasible. It beats the purpose of this plugin which is to embed services by the URL. This is just an image markup which can be simply done with an image tag.

So I'd close this now. I'm still open for more interesting ideas 🙂
